language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
- docker
env:
  global:
  - PINS="metrics:."
  - DISTRO="debian-stable"
  matrix:
  - PACKAGE="metrics" OCAML_VERSION="4.04"
  - PACKAGE="metrics" OCAML_VERSION="4.05"
  - PACKAGE="metrics" OCAML_VERSION="4.06"
